@eDocument.WebApi_HostAddress = http://localhost:5294

GET {{eDocument.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{eDocument.WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "password123"
}

###
